[Interface]
Address = 10.200.0.2/24
PrivateKey = <WG_LXC_PRIVATE_KEY>

PostUp = sysctl -w net.ipv4.ip_forward=1

[Peer]
# AWS EC2
PublicKey = <AWS_EC2_PUBLIC_KEY>
Endpoint = <AWS_EC2_PUBLIC_IP>:51820
AllowedIPs = 10.200.0.0/24
PersistentKeepalive = 25