[Interface]
Address = 10.200.0.10/24
PrivateKey = <ROOT_PRIVATE_KEY>

[Peer]
# AWS EC2
PublicKey = <AWS_EC2_PUBLIC_KEY>
Endpoint = <AWS_EC2_PUBLIC_IP>:51820
AllowedIPs = 10.200.0.0/24, 192.168.1.0/24
PersistentKeepalive = 25