[Interface]
Address = 10.200.0.20/24
PrivateKey = <STANDARD_PRIVATE_KEY>

[Peer]
# AWS EC2
PublicKey = <AWS_EC2_PUBLIC_KEY>
Endpoint = <AWS_EC2_PUBLIC_IP>:51820
AllowedIPs = 10.200.0.0/24, 192.168.1.150/32, 192.168.1.151/32, 192.168.1.152/32
PersistentKeepalive = 25