[Interface]
Address = 10.200.0.1/24
ListenPort = 51820
PrivateKey = <SERVER_PRIVATE_KEY>

#Enable forwarding/routing
Postup = sysctl -w net.ipv4.ip_forward=1

[Peer]
# Proxmox WireGuard LXC
PublicKey = <PROXMOX_PUBLIC_KEY>
AllowedIPs = 10.200.0.2/32, 192.168.1.0/24

[Peer]
# Root client
PublicKey = <ROOT_PUBLIC_KEY>
AllowedIPs = 10.200.0.10/32

[Peer]
# Standard client
PublicKey = <STANDARD_PUBLIC_KEY>
AllowedIPs = 10.200.0.20/32